# TBP Pipeline MVP - Instruments Configuration
# Contains only ticker definitions and market metadata

metadata:
  version: "0.1.0"
  description: "MVP with 12 tickers (10 stocks + 2 ETFs) from personal portfolio"
  last_updated: "2025-01-08"
  total_instruments: 12

# 12 tickers: 10 stocks + 2 ETFs from personal portfolio
tickers:
  # Priority 1: Mega cap tech (highest liquidity)
  - symbol: "AAPL"
    name: "Apple Inc"
    sector: "Technology"
    asset_class: "stocks"
    priority: 1
    
  - symbol: "MSFT"
    name: "Microsoft Corp"  
    sector: "Technology"
    asset_class: "stocks"
    priority: 1
    
  - symbol: "NVDA"
    name: "NVIDIA Corp"
    sector: "Semiconductors"
    asset_class: "stocks"
    priority: 1
    
  - symbol: "META"
    name: "Meta Platforms Inc"
    sector: "Technology"
    asset_class: "stocks"
    priority: 1

  # Priority 2: Financials  
  - symbol: "JPM"
    name: "JPMorgan Chase & Co"
    sector: "Financials"
    asset_class: "stocks"
    priority: 2
    
  - symbol: "V"
    name: "Visa Inc"
    sector: "Financials"
    asset_class: "stocks"
    priority: 2

  # Priority 3: Diversified sectors
  - symbol: "CVX"
    name: "Chevron Corp"
    sector: "Energy"
    asset_class: "stocks"
    priority: 3
    
  - symbol: "LLY"
    name: "Eli Lilly and Co"
    sector: "Healthcare"
    asset_class: "stocks"
    priority: 3
    
  - symbol: "UNH"
    name: "UnitedHealth Group Inc"
    sector: "Healthcare" 
    asset_class: "stocks"
    priority: 3
    
  - symbol: "WMT"
    name: "Walmart Inc"
    sector: "Consumer"
    asset_class: "stocks"
    priority: 3

  # ETFs for market analysis and diversification
  - symbol: "SPY"
    name: "SPDR S&P 500 ETF Trust"
    sector: "ETF-Broad Market"
    asset_class: "stocks"
    priority: 4
    
  - symbol: "QQQ"
    name: "Invesco QQQ Trust"
    sector: "ETF-Technology"
    asset_class: "stocks"
    priority: 4

# Market metadata
market_info:
  primary_exchange: "US"
  trading_currency: "USD"
  timezone: "America/New_York"
  
  # Market hours (ET)
  market_hours:
    open: "09:30"
    close: "16:00"
    
  # Trading calendar info
  trading_days:
    - "Monday"
    - "Tuesday" 
    - "Wednesday"
    - "Thursday"
    - "Friday"
    
  # Common market holidays (reference only)
  major_holidays:
    - "New Year's Day"
    - "Martin Luther King Jr. Day"
    - "Presidents Day"
    - "Good Friday"
    - "Memorial Day"
    - "Independence Day"
    - "Labor Day"
    - "Thanksgiving Day"
    - "Christmas Day"

# Ticker groupings for processing
ticker_groups:
  high_priority:
    description: "Mega cap stocks - download first"
    symbols: ["AAPL", "MSFT", "NVDA", "META"]
    
  medium_priority:
    description: "Large cap stocks - download second"
    symbols: ["JPM", "V", "CVX", "LLY", "UNH", "WMT"]
    
  etfs:
    description: "ETFs for market analysis"
    symbols: ["SPY", "QQQ"]
    
  all_stocks:
    description: "All individual stocks (excluding ETFs)"
    symbols: ["AAPL", "MSFT", "NVDA", "META", "JPM", "V", "CVX", "LLY", "UNH", "WMT"]
    
  all_symbols:
    description: "All configured instruments"
    symbols: ["AAPL", "MSFT", "NVDA", "META", "JPM", "V", "CVX", "LLY", "UNH", "WMT", "SPY", "QQQ"]

# Data requirements per ticker
data_requirements:
  # All tickers get same treatment for MVP
  default:
    timeframes: ["1d"]              # Daily bars only for MVP
    history_years: 5                # 5 years of historical data
    data_types: ["day_aggs"]        # Daily aggregates from S3
    
  # Future: Different requirements per ticker type
  # high_volume:
  #   timeframes: ["1m", "1h", "1d"]
  #   data_types: ["minute_aggs", "day_aggs", "trades"]
  #   
  # etfs:
  #   timeframes: ["1h", "1d"] 
  #   data_types: ["day_aggs"]

# Validation rules
validation:
  required_fields: ["symbol", "name", "sector", "asset_class"]
  symbol_pattern: "^[A-Z]{1,5}$"           # 1-5 uppercase letters
  max_symbols: 50                          # Safety limit for MVP
  
  # Sector validation
  allowed_sectors:
    - "Technology"
    - "Semiconductors" 
    - "Financials"
    - "Energy"
    - "Healthcare"
    - "Consumer"
    - "ETF-Broad Market"
    - "ETF-Technology"
    - "ETF-Sector"
  
  # Asset class validation  
  allowed_asset_classes:
    - "stocks"
    - "etfs"
    - "crypto"  # Future support